# Generated by Django 5.2.4 on 2025-09-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('excerpt', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('cover_image_alt', models.CharField(blank=True, max_length=125)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blogs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='idx_blogs_slug'), models.Index(fields=['created_at'], name='idx_blogs_created')],
            },
        ),
    ]
