# Generated by Django 5.2.4 on 2025-11-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('products', '0002_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_blogs', to='products.product'),
        ),
    ]
